name: Pytest

on:
  push:
    branches:
      - test

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Pytest
      run: pytest test.py
